name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories, and then upload the result to GitHub Pages."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  FOLDER:
    description: "Path to list files from."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Run Docker Image"
      env:
        FROM: ${{ inputs.FOLDER }}
        DESTINATION: "/.lavender_dir_listing"
      shell: "bash"
      run: "docker run -v ${{ env.FROM }}:/source -v ${{ env.DESTINATION }}:/folder acanxie/lavender-dir-listing:1.1.0"

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "/.lavender_dir_listing"
