name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  FOLDER:
    description: "Folder to list files from."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Run Docker Image"
      shell: "bash"
      run: "docker run -v ${{ inputs.FOLDER }}:/source -v /dict:/folder acanxie/lavender-dir-listing:1.0.0"
