name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  FOLDER:
    description: "Folder to list files from."
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: "actions/setup-python@v4"
      with:
        python-version: "3.x"

    - name: "Install dependencies"
      shell: "bash"
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "Run Python script"
      shell: "bash"
      run: "python3 index.py"

    - name: Upload Pages Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: dict/
