name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories, and then upload the result to GitHub Pages."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  FROM:
    description: "Folder to list files from."
    required: false
    default: "."
  DESTINATION:
    description: "Folder to save the result."
    required: false
    default: "/dict"

runs:
  using: "composite"
  steps:
    - name: "Run Docker Image"
      shell: "bash"
      run: "docker run -v ${{ inputs.FROM }}:/source -v ${{ inputs.DESTINATION }}:/folder acanxie/lavender-dir-listing:1.0.0"

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: "/dict"
