name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories, and then upload the result to GitHub Pages."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  EMAIL:
    description: "Email of the user."
    required: false
    default: ""
  FOLDER:
    description: "Path to list files from."
    required: false
    default: "."
  WEBSITE_URL:
    description: "The user's website URL."
    required: false
    default: ""
  WEBSITE_NAME:
    description: "The user's website name."
    required: false
    default: "Website"

runs:
  using: "composite"
  steps:
    - name: "Run Docker Image"
      env:
        FROM: ${{ inputs.FOLDER }}
        DESTINATION: "/.lavender_dir_listing"
      shell: "bash"
      run: |
        docker run \
          -v ${{ env.FROM }}:/source -v ${{ env.DESTINATION }}:/folder acanxie/lavender-dir-listing:1.2.0 \
          ${{ inputs.EMAIL }} \
          ${{ inputs.WEBSITE_NAME }} \
          ${{ inputs.WEBSITE_URL }} \

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "/.lavender_dir_listing"
