name: "Lavender Dir Listing"
description: "A GitHub action for listing files of GitHub repositories."

author: "Acan"
branding:
  color: "red"
  icon: "upload-cloud"

inputs:
  FOLDER:
    description: "Folder to list files from."
    required: true

runs:
  using: "docker"
  image: "acanxie/lavender-dir-listing:1.0.0"
  args: ["-v", "${{ github.workspace }}:/source", "-v", "/dict:/folder"]
